apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: smarthome
spec:
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
      - name: grocy
        imagePullPolicy: Always
        image: linuxserver/grocy:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9283
        volumeMounts:
          - name: db
            mountPath: /var/www/data
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/Copenhagen"
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: grocy
