apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grocy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - grocy.kristoffer.codes
      secretName: grocy-tls
  rules:
  - host: grocy.kristoffer.codes
    http:
      paths:
      - path: /
        backend:
          serviceName: grocy
          servicePort: 80
