# helm repo add influxdata https://helm.influxdata.com/
# helm repo update
# helm upgrade --install chronograf influxdata/chronograf -f chronograf.yml --namespace monitoring

image:
  repository: chronograf
  tag: 1.8.10

persistence:
  enabled: true
  storageClass: nfs-client

# ingress:
#   enabled: true
#   hostname: influx.kristoffer.codes
#   tls: true
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt
#     secretName: grafana-tls
