# helm repo add influxdata https://helm.influxdata.com/
# helm repo update
# helm upgrade --install telegraf influxdata/telegraf -f telegraf.yml --namespace monitoring

image:
  tag: latest

# volumes:
# - name: telegraf-output-influxdb2
#   configMap:
#     name: "telegraf-output-influxdb2"
# mountPoints:
# - name: telegraf-output-influxdb2
#   mountPath: /etc/telegraf/conf.d
#   subPath: influxdb2.conf

# config:
#   outputs:
#     - influxdb:
#         urls:
#           - "http://influxdb.monitoring:8086"
#         database: "telegraf"
#   inputs:
#     - ping:
#         urls:
#           - "google.com"

config:
  agent:
    interval: "10s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: "$HOSTNAME"
    omit_hostname: false
  processors:
    - enum:
        mapping:
          field: "status"
          dest: "status_code"
          value_mappings:
            healthy: 1
            problem: 2
            critical: 3
  outputs:
    - influxdb:
        urls:
          - "http://influxdb.monitoring:8086"
        database: "telegraf"
  inputs:
    - ping:
        urls:
          - "google.com"
    # - internet_speed:
    #     enable_file_download: false
    #     interval: "30m"
    - statsd:
        service_address: ":8125"
        percentiles:
          - 50
          - 95
          - 99
        metric_separator: "_"
        allowed_pending_messages: 10000
        percentile_limit: 1000
metrics:
  health:
    enabled: false
    service_address: "http://:8888"
    threshold: 5000.0
  internal:
    enabled: true
    collect_memstats: false
