ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - hass.krpetersen.dk
  tls:
  - hosts:
    - hass.krpetersen.dk
    secretName: homeassistant-tls-cert
