persistence:
  enabled: true

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - grafana.krpetersen.dk
  tls:
  - hosts:
    - grafana.krpetersen.dk
    secretName: grafana-tls-cert

namespaceOverride: "monitoring"
