ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  path: /
  hosts:
    - registry.krpetersen.dk
  tls:
  - hosts:
    - registry.krpetersen.dk
    secretName: docker-registry-tls-cert

persistence:
  enabled: true
