# helm repo add grafana https://grafana.github.io/helm-charts
# helm repo update
# helm install grafana grafana/grafana -f grafana.yml --namespace monitoring

image:
  tag: latest
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  path: /
  pathType: Prefix
  hosts:
    - grafana.kristoffer.codes
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.kristoffer.codes

persistence:
  enabled: true
  storageClassName: nfs-client
