# helm repo add grafana https://grafana.github.io/helm-charts
# helm repo update
# helm upgrade --install grafana grafana/grafana -f grafana.yml

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
  - grafana.kristoffer.codes
  tls:
  - hosts:
    - grafana.kristoffer.codes
    secretName: grafana-tls
persistence:
  enabled: true
replicas: 3
