# helm repo add k8s-at-home https://k8s-at-home.com/charts/
# helm repo update
# helm upgrade --install grocy k8s-at-home/grocy -f grocy.yml --namespace smarthome

image:
  tag: latest

env:
  TZ: Europe/Copenhagen

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: grocy.kristoffer.codes
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: grocy-tls
        hosts:
          - grocy.kristoffer.codes

persistence:
  config:
    enabled: true
    storageClass: nfs-client
