apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
spec:
   accessModes:
     - ReadWriteOnce
#   storageClassName: nfs-client
   resources:
       requests:
           storage: 2Gi
