# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo update
# helm upgrade --install redis bitnami/redis -f redis.yml --namespace persistence

image:
  repository: redis
  tag: latest

persistence:
  enabled: true
  storageClassName: nfs-client
